# Generated by Django 5.1.3 on 2024-12-12 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('primary_instructor', models.CharField(max_length=255)),
                ('course_code_new', models.CharField(max_length=50)),
                ('department_code', models.CharField(max_length=50)),
                ('core_code', models.CharField(max_length=50)),
                ('course_group', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('class_group', models.CharField(max_length=50)),
                ('course_name_cn', models.CharField(max_length=255)),
                ('course_name_en', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('enrollment', models.IntegerField()),
                ('male_students', models.IntegerField()),
                ('female_students', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('weeks', models.CharField(max_length=50)),
                ('hours_per_week', models.FloatField()),
                ('course_type_code', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=20)),
                ('class_period', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_summary_cn', models.TextField(blank=True, null=True)),
                ('course_summary_en', models.TextField(blank=True, null=True)),
                ('primary_instructor_code_old', models.CharField(max_length=50)),
                ('course_code_old', models.CharField(max_length=50)),
                ('schedule_code_old', models.CharField(max_length=50)),
                ('schedule_name_old', models.CharField(max_length=100)),
                ('instructor_code_old', models.CharField(max_length=50)),
                ('course_class', models.CharField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_students', to='schedule_courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
